/**
 * Message-related type definitions
 */

export interface Message {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp?: string;
  id?: number;
  images?: string[]; // Array of image URLs/data URLs
  imageIds?: string[]; // Array of cached image IDs for reference
  autonomous?: boolean; // True for messages generated by the autonomy system
  lanPeer?: boolean; // True for messages received from a LAN peer
  sender?: string; // Display name override (e.g. peer persona name for LAN messages)
}

export interface MessageHistory {
  role: 'user' | 'assistant' | 'system';
  content: string;
  images?: string[]; // Array of image URLs/data URLs for vision
}

export interface ChatHistoryEntry {
  id: string;
  persona: string;
  timestamp: string;
  messages: Message[];
}
